# Generated by Django 4.1.4 on 2022-12-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familiar',
            new_name='Familiares',
        ),
    ]
